name: Test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*'
    - '!./Cargo.lock'
    - '!./backend/Cargo.toml'
    - '!./backend/src'
    - '!./frontend/Cargo.toml'
    - '!./frontend/src'
    - '!./.github/workflows/test.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*'
    - '!./Cargo.lock'
    - '!./backend/Cargo.toml'
    - '!./backend/src'
    - '!./frontend/Cargo.toml'
    - '!./frontend/src'
    - '!./.github/workflows/test.yml'

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.66.0

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION }}
        default: true
        components: clippy
    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
    - name: Lint
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --verbose --release -- -D warnings
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --release
